name: Virtually Benevolent
description: Michael Stanclift @vmstan
meta_description: "Your New Jekyll Site, Blogging about stuffs"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://vmstan.github.io'
google_analytics: 'UA-XXXXXXXX-X'

# Details for the RSS feed generator
url:            'http://vmstan.github.io'
author:         'Michael Stanclift'
