# Site settings
title: Virtually Benevolent
author: Michael Stanclift
description: VMware TAM
permalink: /:year/:month/:title
url: vmstan.com
baseurl: ""

# Build settings
port: 4000
exclude: [ "node_modules", "package.json", "*.log", "scripts", "src", "LICENSE" ]

# Markdown
markdown: kramdown
kramdown:
  input: GFM

# Blog settings
permalink: /:year/:month/:title/

# Defaults for post layouts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
      type: "post"
