# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               'Virtually Benevolent'
tagline:             '@vmstan'
description:         'Michael Stanclift: Senior Engineer for AOS in Kansas City. VCAP, EMCIE, CCNA. #vExpert #CiscoChampion'
url:                 'http://vmstan.github.io'
baseurl:             /
paginate:            10
logo:                'false'
domain_name:         'http://vmstan.github.io'
google_analytics:    'UA-XXXXXXXX-X'

# About/contact
author:
  name:              'Michael Stanclift'
  url:               'http://vmstan.com'
  email:             'mx@vmstan.com'
  github:            'vmstan'
  twitter:           'vmstan'
  linkedin:          'stanclift'

# Custom vars
version:             1.0

github:
  repo:              'https://github.com/vmstan/'
